CREATE TABLE IF NOT EXISTS "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "openId" varchar(64) NOT NULL UNIQUE,
  "name" text,
  "email" varchar(320),
  "loginMethod" varchar(64),
  "role" varchar(16) NOT NULL DEFAULT 'user' CHECK ("role" IN ('user', 'admin')),
  "waiterCode" varchar(32) UNIQUE,
  "waiterActive" smallint NOT NULL DEFAULT 1,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  "lastSignedIn" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "table_sessions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sessionToken" varchar(128) NOT NULL UNIQUE,
  "tableNumber" varchar(32) NOT NULL DEFAULT '01',
  "status" varchar(16) NOT NULL DEFAULT 'open' CHECK ("status" IN ('open', 'closed')),
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  "lastActivityAt" timestamptz NOT NULL DEFAULT now(),
  "closedAt" timestamptz,
  "waiterId" integer,
  "viewedAt" timestamptz,
  "attendingWaiterId" integer,
  "attendingSince" timestamptz
);
CREATE INDEX IF NOT EXISTS "table_sessions_status_idx" ON "table_sessions" ("status");
CREATE INDEX IF NOT EXISTS "table_sessions_table_number_idx" ON "table_sessions" ("tableNumber");
CREATE INDEX IF NOT EXISTS "table_sessions_attending_waiter_idx" ON "table_sessions" ("attendingWaiterId");

CREATE TABLE IF NOT EXISTS "table_selections" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sessionId" integer NOT NULL,
  "selectionNumber" integer NOT NULL,
  "subtotal" numeric(10,2) NOT NULL,
  "status" varchar(16) NOT NULL DEFAULT 'PENDING' CHECK ("status" IN ('PENDING', 'PREPARING', 'READY', 'DELIVERED', 'COMPLETED')),
  "notes" text,
  "viewedAt" timestamptz,
  "sentAt" timestamptz,
  "receivedAt" timestamptz,
  "finalizedAt" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "table_selections_session_fk" FOREIGN KEY ("sessionId") REFERENCES "table_sessions"("id") ON DELETE CASCADE,
  CONSTRAINT "table_selections_session_number_unique" UNIQUE ("sessionId", "selectionNumber")
);
CREATE INDEX IF NOT EXISTS "table_selections_session_created_idx" ON "table_selections" ("sessionId", "createdAt");

CREATE TABLE IF NOT EXISTS "table_selection_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "selectionId" integer NOT NULL,
  "productName" varchar(160) NOT NULL,
  "preparation" text,
  "quantity" integer NOT NULL,
  "unitPrice" numeric(10,2) NOT NULL,
  CONSTRAINT "table_selection_items_selection_fk" FOREIGN KEY ("selectionId") REFERENCES "table_selections"("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "table_selection_items_selection_idx" ON "table_selection_items" ("selectionId");

CREATE TABLE IF NOT EXISTS "table_qr_codes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tableNumber" varchar(64) NOT NULL UNIQUE,
  "qrToken" varchar(128) NOT NULL UNIQUE,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "menu_categories" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "restaurantId" varchar(64) NOT NULL DEFAULT 'default',
  "name" varchar(100) NOT NULL,
  "status" varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK ("status" IN ('ACTIVE', 'REMOVED')),
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "menu_categories_restaurant_idx" ON "menu_categories" ("restaurantId");

CREATE TABLE IF NOT EXISTS "menu_products" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "restaurantId" varchar(64) NOT NULL DEFAULT 'default',
  "categoryId" integer NOT NULL,
  "name" varchar(160) NOT NULL,
  "description" text,
  "preparation" text,
  "preparationEn" text,
  "price" numeric(10,2) NOT NULL,
  "imageUrl" text,
  "status" varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK ("status" IN ('ACTIVE', 'INACTIVE', 'REMOVED')),
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  "deletedAt" timestamptz,
  CONSTRAINT "menu_products_category_fk" FOREIGN KEY ("categoryId") REFERENCES "menu_categories"("id")
);
CREATE INDEX IF NOT EXISTS "menu_products_restaurant_status_idx" ON "menu_products" ("restaurantId", "status");
CREATE INDEX IF NOT EXISTS "menu_products_category_idx" ON "menu_products" ("categoryId");
