/* Pátio Solar: máximo de simplicidade, consulta editorial e atendimento humano presencial. */
import { useMemo, useState } from "react";
import { ArrowUp, ChevronDown, ChevronLeft, Heart, Info, Search, SlidersHorizontal, Sparkles, X } from "lucide-react";

type Category = "Todos" | "Entradas" | "Pratos" | "Hambúrgueres" | "Bebidas" | "Sobremesas";
type Tag = "Especial da Casa" | "Mais Pedido" | "Novo" | "Recomendado";
type Product = {
  name: string; category: Exclude<Category, "Todos">; description: string; price: number; image?: string;
  tag?: Tag; available: boolean; ingredients?: string; allergens?: string; spicy?: string; variations?: string;
  portion?: string; preparation?: string; features?: string; combines?: string; popular?: boolean; recommended?: boolean; vegetarian?: boolean;
};

const products: Product[] = [
  { name: "Frango à Zambeziana", category: "Pratos", description: "Frango macio, arroz perfumado, salada fresca e molho de coco com limão.", price: 350, image: "/manus-storage/prato-frango-zambeziana_7f9dffc0.png", tag: "Especial da Casa", available: true, recommended: true, popular: true, ingredients: "Frango, arroz, tomate, cebola, coco e especiarias.", allergens: "Pode conter leite.", spicy: "Médio", portion: "1 porção individual", preparation: "Aproximadamente 20–30 min", features: "Especial da Casa", combines: "Salada ou Coca-Cola", variations: "Acompanhamento: arroz, batata frita ou salada." },
  { name: "Frango Grelhado", category: "Pratos", description: "Peito de frango grelhado com arroz, salada e molho da casa.", price: 300, tag: "Mais Pedido", available: true, recommended: true, popular: true, ingredients: "Frango, arroz, folhas verdes e ervas.", allergens: "Não especificados.", spicy: "Não picante", portion: "1 porção individual", preparation: "Aproximadamente 20 min", features: "Mais Pedido", combines: "Batata frita ou salada", variations: "Acompanhamento: arroz ou salada." },
  { name: "Peixe Grelhado", category: "Pratos", description: "Peixe do dia na brasa, limão tostado, arroz de coco e folhas.", price: 450, image: "/manus-storage/prato-peixe-grelhado_aa2e3916.png", tag: "Recomendado", available: true, recommended: true, ingredients: "Peixe do dia, arroz, coco, limão e folhas verdes.", allergens: "Contém peixe.", spicy: "Não picante", portion: "1 porção individual", preparation: "Aproximadamente 25–35 min", features: "Recomendado", combines: "Água ou salada" },
  { name: "Matapa", category: "Pratos", description: "Folhas de mandioca moídas com amendoim, coco e arroz branco.", price: 300, tag: "Recomendado", available: true, vegetarian: true, ingredients: "Folhas de mandioca, amendoim, coco e arroz.", allergens: "Contém amendoim.", spicy: "Médio", portion: "1 porção individual", preparation: "Aproximadamente 25 min", features: "Vegetariano" },
  { name: "Chamuça", category: "Entradas", description: "Pastel crocante recheado com especiarias e legumes.", price: 50, tag: "Mais Pedido", available: true, ingredients: "Massa, legumes e especiarias.", allergens: "Contém glúten.", spicy: "Médio" },
  { name: "Rissóis", category: "Entradas", description: "Rissóis dourados com recheio cremoso e temperos suaves.", price: 60, available: true, ingredients: "Massa, recheio cremoso e ervas.", allergens: "Contém glúten e leite.", spicy: "Não picante" },
  { name: "Batata frita", category: "Entradas", description: "Batata cortada à mão, crocante por fora e macia por dentro.", price: 100, available: true, ingredients: "Batata, óleo e sal.", allergens: "Não especificados.", spicy: "Não picante" },
  { name: "Hambúrguer Clássico", category: "Hambúrgueres", description: "Carne grelhada, queijo, tomate, cebola e molho da casa.", price: 280, available: true, ingredients: "Pão, carne, queijo, tomate, cebola e molho.", allergens: "Contém glúten e leite.", spicy: "Não picante" },
  { name: "Hambúrguer Especial", category: "Hambúrgueres", description: "Carne grelhada, queijo, cebola caramelizada e molho picante.", price: 350, tag: "Novo", available: true, ingredients: "Pão, carne, queijo, cebola e molho picante.", allergens: "Contém glúten e leite.", spicy: "Picante" },
  { name: "Coca-Cola", category: "Bebidas", description: "Refrigerante servido bem fresco.", price: 80, available: true },
  { name: "Fanta", category: "Bebidas", description: "Refrigerante de laranja servido bem fresco.", price: 80, available: true },
  { name: "Água", category: "Bebidas", description: "Água mineral sem gás.", price: 50, available: true },
  { name: "Sumol", category: "Bebidas", description: "Refrigerante de fruta servido bem fresco.", price: 100, available: true },
  { name: "Gelado", category: "Sobremesas", description: "Uma bola de gelado do dia, cremosa e refrescante.", price: 120, tag: "Novo", available: true, ingredients: "Leite, açúcar e sabor do dia.", allergens: "Contém leite.", spicy: "Não picante" },
  { name: "Salada de Frutas", category: "Sobremesas", description: "Frutas tropicais da estação com hortelã e creme de coco.", price: 150, image: "/manus-storage/sobremesa-salada-frutas_04efab3f.png", tag: "Recomendado", available: true, ingredients: "Frutas tropicais, hortelã e coco.", allergens: "Pode conter leite.", spicy: "Não picante" },
];

const categories: Category[] = ["Todos", "Entradas", "Pratos", "Hambúrgueres", "Bebidas", "Sobremesas"];
const money = (price: number) => `${price.toLocaleString("pt-MZ")} MT`;
const tagClass: Record<Tag, string> = { "Especial da Casa": "tag-house", "Mais Pedido": "tag-popular", Novo: "tag-new", Recomendado: "tag-chef" };

export default function Home() {
  const [category, setCategory] = useState<Category>("Todos");
  const [query, setQuery] = useState("");
  const [priceFilter, setPriceFilter] = useState("todos");
  const [maxPrice, setMaxPrice] = useState("");
  const [selected, setSelected] = useState<Product | null>(null);
  const [showFilters, setShowFilters] = useState(false);
  const [notice, setNotice] = useState(false);
  const [sortBy, setSortBy] = useState("recommended");
  const [showFavorites, setShowFavorites] = useState(false);
  const [favorites, setFavorites] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("patio-zambeze-favorites") || "[]"); } catch { return []; } });

  const filteredProducts = useMemo(() => products.filter((product) => {
    const text = `${product.name} ${product.category}`.toLowerCase();
    const matchesCategory = category === "Todos" || product.category === category;
    const matchesQuery = text.includes(query.toLowerCase());
    const matchesRange = priceFilter === "todos" || (priceFilter === "100" && product.price <= 100) || (priceFilter === "100-250" && product.price > 100 && product.price <= 250) || (priceFilter === "250-500" && product.price > 250 && product.price <= 500) || (priceFilter === "500" && product.price > 500);
    const matchesMax = maxPrice === "" || product.price <= Number(maxPrice);
    const matchesFavorites = !showFavorites || favorites.includes(product.name);
    return matchesCategory && matchesQuery && matchesRange && matchesMax && matchesFavorites;
  }).sort((a, b) => sortBy === "lowest" ? a.price - b.price : sortBy === "highest" ? b.price - a.price : sortBy === "popular" ? Number(b.popular) - Number(a.popular) : Number(b.recommended) - Number(a.recommended)), [category, query, priceFilter, maxPrice, sortBy, showFavorites, favorites]);

  const hasFilters = category !== "Todos" || query !== "" || priceFilter !== "todos" || maxPrice !== "" || sortBy !== "recommended" || showFavorites;
  const recommendedProducts = products.filter((product) => product.recommended).slice(0, 3);
  const toggleFavorite = (name: string) => setFavorites((current) => { const next = current.includes(name) ? current.filter((item) => item !== name) : [...current, name]; localStorage.setItem("patio-zambeze-favorites", JSON.stringify(next)); return next; });
  const clearFilters = () => { setCategory("Todos"); setQuery(""); setPriceFilter("todos"); setMaxPrice(""); setSortBy("recommended"); setShowFavorites(false); };

  const callWaiter = () => { setNotice(true); window.setTimeout(() => setNotice(false), 4200); };

  return <div className="min-h-screen bg-[#F7F2E9] text-[#183A32]">
    <header className="border-b border-[#183A32]/10 bg-[#F7F2E9]/95 px-5 pb-6 pt-5 backdrop-blur-sm sm:px-8">
      <div className="mx-auto flex max-w-6xl items-start justify-between gap-6"><div className="flex items-center gap-3"><img src="/manus-storage/logo-symbol_8f597d73.png" alt="Símbolo Pátio Zambeze" className="h-14 w-14 rounded-full object-cover" /><div><p className="font-sans text-[10px] font-bold uppercase tracking-[0.28em] text-[#C85A3F]">Menu digital</p><h1 className="font-display text-3xl leading-none tracking-[-0.03em] sm:text-4xl">Pátio Zambeze</h1></div></div><div className="hidden max-w-[220px] text-right sm:block"><p className="font-display text-lg leading-tight">Escolha o seu sabor.</p><p className="mt-1 font-sans text-xs leading-relaxed text-[#183A32]/60">Aberto hoje · Atendimento presencial</p></div></div>
      <div className="mx-auto mt-7 max-w-6xl"><label className="sr-only" htmlFor="menu-search">Pesquisar produto</label><div className="search-shell flex items-center gap-3 bg-white px-4 py-3"><Search className="h-5 w-5 text-[#C85A3F]" aria-hidden="true" /><input id="menu-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Pesquisar no menu..." className="w-full bg-transparent font-sans text-sm outline-none placeholder:text-[#183A32]/45" />{query && <button aria-label="Limpar pesquisa" onClick={() => setQuery("")} className="text-[#183A32]/50 transition hover:text-[#C85A3F]"><X className="h-4 w-4" /></button>}</div></div>
    </header>

    <main className="mx-auto max-w-6xl px-5 pb-28 sm:px-8"><section className="recommended-strip mt-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Escolhas da casa</p><h2 className="mt-1 font-display text-2xl">Recomendados</h2></div><Sparkles className="h-5 w-5 text-[#C85A3F]" /></div><div className="recommended-list mt-4">{recommendedProducts.map((product) => <button key={product.name} onClick={() => setSelected(product)} className="recommended-item"><span className="recommended-dot">✦</span><span><strong>{product.name}</strong><small>{money(product.price)}</small></span></button>)}</div></section><section className="pt-7 sm:flex sm:items-end sm:justify-between"><div><p className="eyebrow"><Sparkles className="mr-2 inline h-3.5 w-3.5" /> Feito para partilhar</p><h2 className="mt-2 font-display text-4xl leading-none tracking-[-0.035em] sm:text-5xl">O menu da casa</h2></div><p className="mt-3 max-w-xs font-sans text-sm leading-relaxed text-[#183A32]/60 sm:mt-0 sm:text-right">Sabores de Moçambique, preparados para serem descobertos sem pressa.</p></section>
      <nav className="category-scroll mt-8 flex gap-2 overflow-x-auto pb-2" aria-label="Categorias">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`category-pill ${category === item ? "category-pill-active" : ""}`}>{item}</button>)}</nav>
      <section className="mt-4 border-y border-[#183A32]/10 py-3"><button onClick={() => setShowFilters(!showFilters)} className="flex w-full items-center justify-between text-left font-sans text-sm font-semibold"><span className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4 text-[#C85A3F]" /> Filtrar por preço</span><ChevronDown className={`h-4 w-4 transition-transform ${showFilters ? "rotate-180" : ""}`} /></button>{showFilters && <div className="filter-panel mt-4 grid gap-3 sm:grid-cols-2"><select value={priceFilter} onChange={(event) => setPriceFilter(event.target.value)} className="field-control"><option value="todos">Todos os preços</option><option value="100">Até 100 MT</option><option value="100-250">100–250 MT</option><option value="250-500">250–500 MT</option><option value="500">Acima de 500 MT</option></select><label className="field-control flex items-center gap-2"><input value={maxPrice} onChange={(event) => setMaxPrice(event.target.value.replace(/\D/g, ""))} inputMode="numeric" placeholder="Preço máximo" className="w-full bg-transparent outline-none" /><span className="text-xs text-[#183A32]/50">MT</span></label></div>}</section>
      <div className="menu-tools mt-5"><button onClick={() => setShowFavorites(!showFavorites)} className={`favorites-toggle ${showFavorites ? "favorites-toggle-active" : ""}`}><Heart className="h-4 w-4" fill={showFavorites ? "currentColor" : "none"} /> Meus favoritos <span>{favorites.length}</span></button><label className="sort-control">Ordenar por<select value={sortBy} onChange={(event) => setSortBy(event.target.value)}><option value="recommended">Recomendados</option><option value="lowest">Menor preço</option><option value="highest">Maior preço</option><option value="popular">Mais populares</option></select></label>{hasFilters && <button onClick={clearFilters} className="clear-filters"><X className="h-3.5 w-3.5" /> Limpar filtros</button>}</div><div className="editorial-rule mt-8"><div><p className="eyebrow">{category === "Todos" ? "Da cozinha para a mesa" : `Seleção · ${category}`}</p><h3 className="mt-2 font-display text-2xl">{showFavorites ? "Os meus favoritos" : category === "Todos" ? "Para começar" : category}</h3></div><span className="font-sans text-xs font-semibold uppercase tracking-[0.16em] text-[#183A32]/45">{filteredProducts.length} itens</span></div>
      {filteredProducts.length > 0 ? <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filteredProducts.map((product, index) => <div key={product.name} role="button" tabIndex={0} onClick={() => setSelected(product)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setSelected(product); }} className={`product-card text-left ${!product.available ? "product-card-unavailable" : ""}`} style={{ animationDelay: `${index * 40}ms` }}>
        {product.image ? <img loading="lazy" src={product.image} alt={product.name} className="product-image" /> : <div className="product-image product-image-placeholder"><span className="fallback-mark" aria-hidden="true">☼</span><span>{product.category === "Bebidas" ? "Bebida fresca" : product.category}</span></div>}
        <div className="p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-display text-xl leading-tight">{product.name}</p><p className="mt-1.5 line-clamp-2 font-sans text-sm leading-relaxed text-[#183A32]/60">{product.description}</p></div><div className="flex items-center gap-2"><span className="price-tag shrink-0">{money(product.price)}</span><button type="button" aria-label={favorites.includes(product.name) ? `Remover ${product.name} dos favoritos` : `Adicionar ${product.name} aos favoritos`} onClick={(event) => { event.stopPropagation(); toggleFavorite(product.name); }} className={`favorite-button ${favorites.includes(product.name) ? "favorite-button-active" : ""}`}><Heart className="h-4 w-4" fill={favorites.includes(product.name) ? "currentColor" : "none"} /></button></div></div><div className="mt-3 flex flex-wrap items-center gap-2">{product.tag && <span className={`product-tag ${tagClass[product.tag]}`}>{product.tag}</span>}{product.vegetarian && <span className="product-tag tag-veg">Vegetariano</span>}{!product.available && <span className="product-tag tag-unavailable">Indisponível no momento</span>}</div><p className="mt-4 font-sans text-[10px] font-bold uppercase tracking-[0.18em] text-[#C85A3F]">Ver detalhes <ChevronDown className="ml-1 inline h-3 w-3 -rotate-90" /></p></div>
      </div>)}</div> : <div className="empty-state mt-5"><p className="font-display text-2xl">Nenhum produto encontrado.</p><p className="mt-2 font-sans text-sm text-[#183A32]/60">Tente outra categoria, palavra ou faixa de preço.</p></div>}
      <section className="waiter-note mt-12 flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><p className="eyebrow">Atendimento presencial</p><p className="mt-2 font-display text-2xl leading-tight">Para fazer o pedido, chame o garçom.</p></div><button onClick={callWaiter} className="waiter-button">Lembrar-me</button></section>
      <button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="back-top"><ArrowUp className="h-4 w-4" /> Voltar ao topo</button><section className="restaurant-info mt-10 grid gap-5 border-t border-[#183A32]/12 pt-6 sm:grid-cols-2"><div><p className="eyebrow">Sobre o restaurante</p><h3 className="mt-2 font-display text-2xl">Pátio Zambeze</h3><p className="mt-2 max-w-sm font-sans text-sm leading-relaxed text-[#183A32]/62">Um espaço para descobrir sabores de Moçambique com calma. Gostou de algum prato? Aguarde pelo garçom para fazer o pedido.</p></div><div className="font-sans text-sm leading-7 text-[#183A32]/62 sm:text-right"><p>Horário: confirme com a equipa da casa</p><p>Para informações, fale com o garçom</p><p className="font-semibold text-[#C85A3F]">Digitalizar o menu, não o atendimento.</p></div></section>
    </main>

    {selected && <div className="modal-backdrop" role="presentation" onClick={() => setSelected(null)}><article className="detail-modal" role="dialog" aria-modal="true" aria-labelledby="product-title" onClick={(event) => event.stopPropagation()}><button onClick={() => setSelected(null)} aria-label="Voltar ao menu" className="modal-close"><ChevronLeft className="h-5 w-5" /> <span>Voltar ao menu</span></button>{selected.image && <img src={selected.image} alt={selected.name} className="h-56 w-full object-cover sm:h-72" />}<div className="p-6 sm:p-8"><div className="flex flex-wrap items-center gap-2"><p className="eyebrow">{selected.category}</p>{selected.tag && <span className={`product-tag ${tagClass[selected.tag]}`}>{selected.tag}</span>}{!selected.available && <span className="product-tag tag-unavailable">Indisponível</span>}</div><h2 id="product-title" className="mt-3 font-display text-4xl leading-none">{selected.name}</h2><p className="mt-5 font-sans text-base leading-relaxed text-[#183A32]/70">{selected.description}</p><p className="mt-7 font-sans text-2xl font-bold text-[#C85A3F]">{money(selected.price)}</p><div className="detail-grid mt-7 border-t border-[#183A32]/10 pt-5">{selected.ingredients && <div><p className="detail-label">Ingredientes principais</p><p>{selected.ingredients}</p></div>}{selected.allergens && <div><p className="detail-label">Alergénios</p><p>{selected.allergens}</p></div>}{selected.spicy && <div><p className="detail-label">Picante</p><p>{selected.spicy === "Não picante" ? "🌶️ Não picante" : selected.spicy === "Médio" ? "🌶️🌶️ Médio" : "🌶️🌶️🌶️ Picante"}</p></div>}{selected.portion && <div><p className="detail-label">Porção</p><p>{selected.portion}</p></div>}{selected.preparation && <div><p className="detail-label">Preparação</p><p>⏱️ {selected.preparation}</p></div>}{selected.features && <div><p className="detail-label">Características</p><p>{selected.features}</p></div>}{selected.combines && <div><p className="detail-label">Combina bem com</p><p>{selected.combines}</p></div>}{selected.variations && <div><p className="detail-label">Opções informativas</p><p>{selected.variations}</p></div>}</div><div className="mt-7 flex gap-2 border-t border-[#183A32]/10 pt-5 font-sans text-sm leading-relaxed text-[#183A32]/65"><Info className="mt-0.5 h-4 w-4 shrink-0 text-[#C85A3F]" /> Para pedir este prato, chame o garçom da sua mesa.</div></div></article></div>}
    {notice && <div className="notice" role="status">Por favor, chame o garçom da sua mesa para fazer o pedido.</div>}
  </div>;
}
