import React from "react";

type ReceiptItem = { id?: number | string; productName: string; quantity: number; unitPrice: number; subtotal: number };
type ReceiptSelection = { id: number | string; selectionNumber: number; createdAt: Date | string | number; subtotal: number; status?: string; items: ReceiptItem[] };

export function ThermalReceipt({ selections, total, width = "58mm", language = "pt", className = "", tableLabel, waiterName, waiterCode, logoUrl = "/manus-storage/logo-symbol_8f597d73.png", restaurantName = "Pátio Zambeze", restaurantPhone = "+258 84 000 0000", restaurantWhatsapp = "+258 84 000 0000", restaurantAddress = "Av. Marginal, Maputo" }: { selections: ReceiptSelection[]; total: number; width?: "58mm" | "80mm"; language?: "pt" | "en"; className?: string; tableLabel?: string; waiterName?: string | null; waiterCode?: string | null; logoUrl?: string; restaurantName?: string; restaurantPhone?: string; restaurantWhatsapp?: string; restaurantAddress?: string }) {
  const money = (value: number) => `${value.toFixed(2)} MT`;
  const dateTime = (value: Date | string | number) => new Date(value).toLocaleString(language === "pt" ? "pt-PT" : "en-GB", { dateStyle: "short", timeStyle: "medium" });
  const now = new Date().toLocaleString(language === "pt" ? "pt-PT" : "en-GB", { dateStyle: "short", timeStyle: "short" });
  const copy = language === "pt" ? { history: "HISTÓRICO MESA", selection: "Seleção", subtotal: "Subtotal:", total: "TOTAL ESTIMADO:", confirm: "Confirme os valores com o garçom.", thanks: "Obrigado!", status: "Estado:" } : { history: "TABLE HISTORY", selection: "Selection", subtotal: "Subtotal:", total: "ESTIMATED TOTAL:", confirm: "Confirm the amounts with the waiter.", thanks: "Thank you!", status: "Status:" };
  const statusLabel = (status?: string) => ({ PENDING: language === "pt" ? "Pendente" : "Pending", PREPARING: language === "pt" ? "Em preparação" : "Preparing", READY: language === "pt" ? "Pronto" : "Ready", DELIVERED: language === "pt" ? "Entregue" : "Delivered", COMPLETED: language === "pt" ? "Concluído" : "Completed" }[status ?? "PENDING"] ?? status ?? (language === "pt" ? "Pendente" : "Pending"));

  return <section className={`receipt-print receipt-${width} ${className}`} aria-label={language === "pt" ? "Recibo térmico" : "Thermal receipt"}><header><div className="receipt-header-brand">{logoUrl && <img className="receipt-logo" src={logoUrl} alt="" />}{restaurantName && <strong>{restaurantName.toUpperCase()}</strong>}</div><div className="receipt-header-contact"><span>{restaurantPhone}</span><span>{language === "pt" ? `WhatsApp: ${restaurantWhatsapp}` : `WhatsApp: ${restaurantWhatsapp}`}</span><span>{restaurantAddress}</span></div><div className="receipt-header-title"><span>{copy.history}</span></div><div className="receipt-header-meta">{tableLabel && <span>{language === "pt" ? `MESA ${tableLabel}` : `TABLE ${tableLabel}`}</span>}{waiterName && <span>{language === "pt" ? `GARÇOM: ${waiterName}` : `WAITER: ${waiterName}`}</span>}{waiterCode && <span>{language === "pt" ? `ID: ${waiterCode}` : `ID: ${waiterCode}`}</span>}<time>{now}</time></div></header>{selections.map((selection) => <section key={selection.id} className="receipt-selection"><strong>{copy.selection} {selection.selectionNumber}</strong><span className="receipt-selection-status">{copy.status} {statusLabel(selection.status)}</span><time className="receipt-selection-time">{dateTime(selection.createdAt)}</time><span className="receipt-rule">--------------------------------</span>{selection.items.map((item, index) => <div key={`${selection.id}-${item.id ?? index}`} className="receipt-item"><span>{item.productName}</span><span>{item.quantity} × {money(item.unitPrice)} <b>{money(item.subtotal)}</b></span></div>)}<div className="receipt-subtotal"><span>{copy.subtotal}</span><b>{money(selection.subtotal)}</b></div></section>)}<div className="receipt-total"><span>{copy.total}</span><strong>{money(total)}</strong></div><p>{copy.confirm}</p><footer>{copy.thanks}</footer></section>;
}
